feat(cloudflare): add healthchecks

diff --git a/apps/cloudflare/configmap.yaml b/apps/cloudflare/configmap.yaml
--- a/apps/cloudflare/configmap.yaml
+++ b/apps/cloudflare/configmap.yaml
@@ -20,8 +20,26 @@ data:
     set -o errexit
     set -o nounset
 
-    [ -z "${ZONE_ID}" ] && echo "ERROR: ZONE_ID is not set!" && exit 1
-    [ -z "${AUTH_TOKEN}" ] && echo "ERROR: AUTH_TOKEN is not set!" && exit 1
+    function healthchecks {
+      [ -n "${HEALTHCHECKS_URL}" ] &&
+        curl -fsS "${HEALTHCHECKS_URL}$([ "${1}" != 0 ] && echo -n /fail)" > /dev/null
+    }
+
+    function notify {
+      healthchecks 1
+      echo "ERROR: Unable to fetch firewall events!"
+    }
+
+    trap notify ERR
+
+    [ -z "${ZONE_ID}" ] && \
+      echo "ERROR: ZONE_ID is not set!" && \
+      healthchecks 1 && \
+      exit 1
+    [ -z "${AUTH_TOKEN}" ] && \
+      echo "ERROR: AUTH_TOKEN is not set!" && \
+      healthchecks 1 && \
+      exit 1
 
     DEBUG=${DEBUG:-false}
     INDEX_NAME=${INDEX_NAME:-cloudflare_fw_events}
@@ -30,6 +48,7 @@ data:
     MINUTES=${MINUTES:-180}
     [ -n "${MINUTES##*[0-9]*}" ] && \
       echo "MINUTES must be INT" && \
+      healthchecks 1 && \
       exit 1
 
     END_DATE=${END_DATE:-$(date --date today +'%Y-%m-%d %H:%M:%S')}
@@ -92,10 +111,12 @@ data:
 
     [ -n "$(jq '.errors[]?' <<< ${cf_response})" ] && \
       echo "ERROR: cannot get Cloudflare firewall events. $(jq '.errors[]?' <<< ${cf_response})" && \
+      healthchecks 1 && \
       exit 1
 
     [ -z "$(jq '.data.viewer.zones[0].firewallEventsAdaptive[]?' <<< ${cf_response})" ] && \
       echo "INFO: no firewall events found" && \
+      healthchecks 0 && \
       exit 0
 
     # check if pipeline for user agent exists
@@ -134,6 +155,7 @@ data:
 
       [ "$(jq '.acknowledged?' <<< ${pipeline_response})" != true ] && \
         echo "ERROR: cannot create pipeline. $(jq '.error?' <<< ${pipeline_response})" && \
+        healthchecks 1 && \
         exit 1
     fi
 
@@ -149,3 +171,5 @@ data:
 
     [ "$DEBUG" == "true" ] && \
       echo "DEBUG: elasticsearch response: $(jq . <<< ${elastic_response})"
+
+    healthchecks 0
